#' MERLIN \code{npartbl} Object
#'
#' Returns an S3 object of class \code{npartbl} which is basically
#' a cleaner version of MERLIN's \code{fam_nonparametric.tbl} file.
#'
#' MERLIN's \code{--tabulate} option is used to output convenient tables
#' summarising linkage analysis results in two files:
#' \code{fam_parametric.tbl} and \code{fam_nonparametric.tbl}.
#'
#' The \code{fam_nonparametric.tbl} file will be output if MERLIN is run with
#' at least one of the options \code{--npl} or \code{--pairs}.
#' These compute a LOD score using the Kong and Cox linear model, which is found
#' in the 'LOD' column. The two options are
#' designated in the 'ANALYSIS' column of the file by character strings containing
#' 'ALL' and 'pairs', respectively.
#'
#' If the \code{--exp} option is also specified,
#' an additional LOD score is calculated using the
#' Kong and Cox exponential mode. This is found in the 'ExLOD' column.
#'
#' If the family consists of a single affected sibpair, the 'ALL' and 'pairs'
#' statistics will be identical. The 'pairs' statistic also considers sharing
#' within inbred individuals. For more information, see MERLIN's website:
#' \url{http://csg.sph.umich.edu/abecasis/merlin/index.html}
#'
#' @param npartbl The name of a \code{fam_nonparametric.tbl}
#' file output by MERLIN
#'
#' @return S3 object of class \code{npartbl}, which is
#' a list with:
#' \itemize{
#'   \item npartbl: data.frame with 4 or 5* columns (chr, pos, analysis, lod, exlod*)
#'   \item chrom: character vector of length 1
#'   \item n_markers: character vector of length 1
#'   \item merlin_options: character vector of length 3, indicating
#'   the options inferred to have been supplied to MERLIN for the nonparametric
#'   linkage analysis
#'   \item pos_range: numeric vector of length 2 giving range of pos column
#'   }
#'
#' @examples
#' npartbl_obj <- npartbl("merlin_10_famA-nonparametric.tbl")
#'
#' @export
npartbl <- function(npartbl) {

  stopifnot(!missing(npartbl))
  if (is.character(npartbl) && length(npartbl) == 1) {
    npartbl <- read_merlin_npartbl(npartbl)
  } else {
    stop("You need to give the full path to the nonparametric.tbl file.")
  }
  names(npartbl) <- tolower(names(npartbl))
  required_cols <- c("chr", "pos", "analysis", "lod")
  stopifnot(all(required_cols %in% names(npartbl)))
  chrom <- unique(npartbl$chr)
  stopifnot(length(chrom) == 1, chrom %in% 1:23)

  # Get pos limits for plotting
  pos_range <- setNames(range(npartbl$pos), c("min_pos", "max_pos"))


  # Guess which MERLIN options were specified
  merlin_options <- c(npl = FALSE, pairs = FALSE, exp = FALSE)
  if ("exlod" %in% names(npartbl)) {
    merlin_options["exp"] <- TRUE
    required_cols <- c(required_cols, "exlod")
  }
  npartbl <- npartbl[required_cols]

  atab <- table(npartbl[["analysis"]])
  # if two counts, should be same
  stopifnot(length(atab) %in% c(1, 2),
            abs(max(atab) - min(atab)) < 0.01)
  npl_atab <- grep("all", names(atab), ignore.case = TRUE)
  pairs_atab <- grep("pairs", names(atab), ignore.case = TRUE)
  if (length(npl_atab) == 1 && length(pairs_atab) == 1 && npl_atab != pairs_atab) {
    merlin_options["npl"] <- merlin_options["pairs"] <- TRUE
  } else if (length(npl_atab) == 1 && length(pairs_atab) == 0 && length(atab) == 1) {
    merlin_options["npl"] <- TRUE
  } else if (length(npl_atab) == 0 && length(pairs_atab) == 1 && length(atab) == 1) {
    merlin_options["pairs"] <- TRUE
  } else {
    stop("You haven't used MERLIN with the --npl or --pairs option. ",
               "This file was probably not generated by MERLIN. Oops.")
  }

  npl_ind <- grep("all", npartbl$analysis, ignore.case = TRUE)
  pairs_ind <- grep("pairs", npartbl$analysis, ignore.case = TRUE)
  npartbl$analysis[npl_ind] <- "all"
  npartbl$analysis[pairs_ind] <- "pairs"

  structure(list(npartbl = npartbl,
                 chrom = chrom,
                 merlin_options = merlin_options,
                 n_markers = (nrow(npartbl) / 2),
                 pos_range = pos_range),
            class = "npartbl")
}

#' Get \code{npartbl} Table
#'
#' @param npartbl An object of class \code{npartbl}.
#'
#' @return A data.frame with the chromosome, position, analysis,
#' lod and exlod columns from a \code{npartbl} object.
#'
#' @examples
#' get_npartbl(npartbl("fam_nonparametric.tbl"))
#'
#' @export
get_npartbl <- function(npartbl) {
  stopifnot(inherits(npartbl, "npartbl"))
  npartbl$npartbl
}


#' Print Head, Middle and Tail of \code{npartbl} Table
#'
#' Prints the head, middle and tail of a \code{npartbl} table.
#'
#' @param npartbl An object of class \code{npartbl}.
#' @param n Number of rows to show in the head, middle and tail
#'
#' @export
print.npartbl <- function(npartbl, n = 6L) {
  stopifnot(inherits(npartbl, "npartbl"))
  stopifnot(length(n) == 1L, is.numeric(n), n > 0)
  if (n > 100L) {
    stop(paste("Giving an n of", n, "will clutter your screen.",
               "Use n lower than 100."))
  }
  tbl <- get_npartbl(npartbl)
  print(head(tbl, n = n))
  cat("--------\n")
  nr <- nrow(tbl)
  midn <- floor(n / 2)
  print(tbl[((nr / 2) - midn + 1):((nr / 2) + midn), ])
  cat("--------\n")
  print(tail(tbl))
}

#' Return Summary of \code{npartbl} Object
#'
#' @param npartbl An object of class \code{npartbl}.
#'
#' @return A list (of class \code{summary.npartbl}) containing summary
#' information about the \code{npartbl} object.
#'
#' @export
summary.npartbl <- function(npartbl) {
  stopifnot(inherits(npartbl, "npartbl"))
  structure(list(chrom = npartbl$chrom,
                 n_markers = npartbl$n_markers,
                 merlin_options = npartbl$merlin_options,
                 pos_range = npartbl$pos_range),
            class = "summary.npartbl")
}

#' Print Summary of \code{npartbl} Object
#'
#' @param npartbl An object of class \code{summary.npartbl}
#'
#' @method print summary.npartbl
#' @export
print.summary.npartbl <- function(npartbl) {
  stopifnot(inherits(npartbl, "summary.npartbl"))
  cat("MERLIN nonparametric.tbl\n",
      "--------------------------\n",
      "Chromosome number: ", npartbl$chrom, "\n",
      "Chromosome range:\n", sep = "")
  print(npartbl$pos_range)
  cat("Number of markers: ", npartbl$n_markers, "\n",
      "MERLIN nonparametric options used:\n", sep = "")
  print(npartbl$merlin_options)
}
