#' Read MERLIN \code{parametric.tbl}
#'
#' Read the \code{parametric.tbl} file output by MERLIN.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame} with the columns
#' @export
#'
#' @examples read_merlin_partbl("merlin_chr13-parametric.tbl")
read_merlin_partbl <- function(fname, verbose = TRUE) {
  partbl <- read.table(fname, header = TRUE, comment.char = "",
                       stringsAsFactors = FALSE)
  names(partbl) <- tolower(names(partbl))
  required_cols <- c("chr", "pos", "label", "model", "lod", "alpha", "hlod")
  stopifnot(all(required_cols == names(partbl)))
  if (nrow(partbl) > 0) {
    chrom <- unique(partbl$chr)
    stopifnot(length(chrom) == 1, chrom %in% 1:23)
    gen_model <- unique(partbl$model)
    if (length(gen_model) != 1) {
      stop("You have probably specified more than one model in MERLIN's ",
           "--model input file. Oops.")
    }
    # See if 100*pos and label are the same
    # If so, rename label to pos and remove
    x <- (100 * partbl$pos) - partbl$label
    stopifnot(all(x < 0.0001))
  } else {
    if (verbose) {
      message("'", fname, "'\n",
              "is empty. It is probably for chrX and MERLIN didn't output\n",
              "LOD scores for it since it was extremely unlikely to contain\n",
              "the disease-causing mutation under the selected genetic model.\n",
              "Returning a 0-row data.frame. This won't be shown in a plot.")
    }
  }
  partbl$pos <- partbl$label
  partbl$label <- NULL
  return(partbl)
}

#' Read MERLIN \code{fam_nonparametric.tbl}
#'
#' Read the \code{fam_nonparametric.tbl} file output by MERLIN
#'
#' The \code{fam_nonparametric.tbl} file contains two rows at the
#' beginning of each 'all' and/or 'pairs' subtable, which
#' indicate the maximum possible scores for the specific dataset.
#' These rows are ignored by using the comment.char = "n"
#' option in \code{\link{read.table}}, which works since only these rows
#' contain an 'n' character. This is a bit hacky, but it should always work.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame}.
#' @export
#'
#' @examples read_merlin_npartbl("merlin_13_famA-nonparametric.tbl")
read_merlin_npartbl <- function(fname, verbose = TRUE) {
  npartbl <- read.table(fname, header = TRUE, comment.char = "n",
                        sep = "\t", stringsAsFactors = FALSE)
  names(npartbl) <- tolower(names(npartbl))
  required_cols <- c("chr", "pos", "analysis", "lod")
  stopifnot(all(required_cols %in% names(npartbl)))
  if (nrow(npartbl) > 0) {
    chrom <- unique(npartbl$chr)
    stopifnot(length(chrom) == 1, chrom %in% 1:23)
    # Check that all = pairs
    atab <- table(npartbl[["analysis"]])
    # if two counts, should be same
    stopifnot(length(atab) %in% c(1, 2),
              abs(max(atab) - min(atab)) < 0.001)
  } else {
    if (verbose) {
      message("'", fname, "'\n",
              "is empty. It is probably for chrX and MERLIN didn't output\n",
              "LOD scores for it since it was extremely unlikely to contain\n",
              "the disease-causing mutation under the selected genetic model.\n",
              "Returning a 0-row data.frame. This won't be shown in a plot.")
    }
  }
  if ("exlod" %in% names(npartbl)) {
    required_cols <- c(required_cols, "exlod")
  }
  npartbl <- npartbl[required_cols]
  npartbl

}


#' Read MERLIN \code{fam.dat}
#'
#' Read the \code{fam.dat} file generated by LDG for MERLIN
#'
#' The \code{fam.dat} file contains two columns: symbol and description.
#' This file is required to describe the final M + 1 columns in the \code{fam.ped}
#' file, where M is the number of markers used in the analysis and the last column
#' is the affectedness status (the first five columns are always
#' the same - FamID, IndID, PatID, MatID and Gender). Therefore the \code{fam.dat}
#' file will contain M + 1 rows.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame} with two columns (symbol and description) and M + 1
#'         rows, where M is the number of markers used in the analysis and the last
#'         row describes the phenotype of interest.
#' @export
#'
#' @examples read_merlin_dat("merlin_13_famA.dat")
read_merlin_dat <- function(fname) {
  read.table(fname, col.names = c("Symbol", "Description"), stringsAsFactors = FALSE)
}

#' Read MERLIN \code{fam.map}
#'
#' Read the \code{fam.map} file generated by LDG for MERLIN
#'
#' The \code{fam.map} file contains three columns: chromosome, marker name, and
#' marker position in centimorgans.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame} with three columns (chromosome, name and position)
#' and M rows, where M is the number of markers used in the analysis.
#' @export
#'
#' @examples read_merlin_map("merlin_13_famA.map")
read_merlin_map <- function(fname) {
  read.table(fname, header = TRUE, stringsAsFactors = FALSE)
}

#' Read MERLIN \code{fam.ped}
#'
#' Read the \code{fam.ped} file generated by LDG for MERLIN
#'
#' The \code{fam.ped} file contains N rows and 5 + M + 1 columns, where N is
#' the number of samples, M is the number of markers and the last column
#' is the affectedness status (the first five columns are always
#' the same - FamID, IndID, PatID, MatID and Gender).
#'
#' @param fname The file name to read.
#'
#' @return A \code{matrix} with N rows and 5 + M + 1 columns
#' (refer to the details section).
#'
#' @export
#'
#' @examples read_merlin_ped("merlin_13_famA.ped")
read_merlin_ped <- function(fname) {
  ped <- read.table(fname, header = FALSE, stringsAsFactors = FALSE)
  as.matrix(ped)
}