#' Read MERLIN \code{fam_parametric.tbl}
#'
#' Read the \code{fam_parametric.tbl} file output by MERLIN.
#'
#' MERLIN's \code{--tabulate} option outputs convenient tables summarising
#' linkage analysis results in two tables:
#' \code{fam_nonparametric.tbl} and \code{fam_parametric.tbl}.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame}.
#' @export
#'
#' @examples read_merlin_partbl("merlin_13_famA-parametric.tbl")
read_merlin_partbl <- function(fname) {
  read.table(fname, header = TRUE, comment.char = "", stringsAsFactors = FALSE)
}

#' Read MERLIN \code{fam_nonparametric.tbl}
#'
#' Read the \code{fam_nonparametric.tbl} file output by MERLIN
#'
#' MERLIN's \code{--tabulate} option outputs convenient tables summarising
#' linkage analysis results in two tables:
#' \code{fam_nonparametric.tbl} and \code{fam_parametric.tbl}.
#'
#' The \code{fam_nonparametric.tbl} file will be useful if MERLIN was run with
#' at least one of the options \code{--npl}, \code{--pairs} or \code{--exp}.
#' The first two compute a LOD score using the Kong and Cox linear model, and are
#' designated in the file as 'all' and 'pairs', respectively;
#' the third complements the LOD score by computing an ExLOD score using the
#' Kong and Cox exponential mode.
#'
#' The \code{fam_nonparametric.tbl} file contains two rows at the
#' beginning of each \code{all} and/or \code{pairs} subtable, which
#' indicate the maximum possible scores for the specific dataset.
#' These rows are ignored by using the comment.char = "n"
#' option in \code{\link{read.table}}, which works since only these rows
#' contain an 'n' character. This is a bit hacky, but it should always work.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame}.
#' @export
#'
#' @examples read_merlin_npartbl("merlin_13_famA-nonparametric.tbl")
read_merlin_npartbl <- function(fname) {
  read.table(fname, header = TRUE, comment.char = "n", sep = "\t", stringsAsFactors = FALSE)
}


#' Read MERLIN \code{fam.dat}
#'
#' Read the \code{fam.dat} file generated by LDG for MERLIN
#'
#' The \code{fam.dat} file contains two columns: symbol and description.
#' This file is required to describe the final M + 1 columns in the \code{fam.ped}
#' file, where M is the number of markers used in the analysis and the last column
#' is the affectedness status (the first five columns are always
#' the same - FamID, IndID, PatID, MatID and Gender). Therefore the \code{fam.dat}
#' file will contain M + 1 rows.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame} with two columns (symbol and description) and M + 1
#'         rows, where M is the number of markers used in the analysis and the last
#'         row describes the phenotype of interest.
#' @export
#'
#' @examples read_merlin_dat("merlin_13_famA.dat")
read_merlin_dat <- function(fname) {
  read.table(fname, col.names = c("Symbol", "Description"), stringsAsFactors = FALSE)
}

#' Read MERLIN \code{fam.map}
#'
#' Read the \code{fam.map} file generated by LDG for MERLIN
#'
#' The \code{fam.map} file contains three columns: chromosome, marker name, and
#' marker position in centimorgans.
#'
#' @param fname The file name to read.
#'
#' @return A \code{data.frame} with three columns (chromosome, name and position)
#' and M rows, where M is the number of markers used in the analysis.
#' @export
#'
#' @examples read_merlin_map("merlin_13_famA.map")
read_merlin_map <- function(fname) {
  read.table(fname, header = TRUE, stringsAsFactors = FALSE)
}

#' Read MERLIN \code{fam.ped}
#'
#' Read the \code{fam.ped} file generated by LDG for MERLIN
#'
#' The \code{fam.ped} file contains N rows and 5 + M + 1 columns, where N is
#' the number of samples, M is the number of markers and the last column
#' is the affectedness status (the first five columns are always
#' the same - FamID, IndID, PatID, MatID and Gender).
#'
#' @param fname The file name to read.
#'
#' @return A \code{matrix} with N rows and 5 + M + 1 columns
#' (refer to the details section).
#'
#' @export
#'
#' @examples read_merlin_ped("merlin_13_famA.ped")
read_merlin_ped <- function(fname) {
  ped <- read.table(fname, header = FALSE, stringsAsFactors = FALSE)
  as.matrix(ped)
}